name: Hyperlink link checker
description: Run hyperlink link checker on a folder of static HTML
branding:
  icon: bookmark
  color: purple
inputs:
  args:
    description: CLI arguments to hyperlink
    required: true

runs:
  using: composite
  steps:
    - name: Download Hyperlink
      run: |
        set -x
        cd ${{ github.action_path }}
        sh scripts/install.sh
      shell: bash

    - name: Run Hyperlink
      run: ~/.cargo/bin/hyperlink ${{ inputs.args }} --github-actions
      shell: bash
